# image: https://hub.docker.com/_/tomcat

version: '3.8'
services:
  tomcat:
    container_name: ${APP_NAME}
    image: tomcat:${APP_VERSION}
    restart: always
    ports:
      - '${APP_HTTP_PORT}:8080'
    volumes:
     - tomcat:/usr/local/tomcat

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  tomcat:
